stages:
  - test

before_script:
  - echo ${YC_CI_LOCKBOX_KEY} | base64 -d > /tmp/sa-key.json
  - command -v curl >/dev/null || apk add --no-cache curl
  - command -v jq >/dev/null || apk add --no-cache jq
  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr -n
  - yc config profile create sa-profile
  - yc config set service-account-key /tmp/sa-key.json 

getsecret:
  stage: test
  image: bash
  script:
    # Получаем секрет
    - export VALUE_OF_YC_CI_SECRET_ID=`yc lockbox payload get --id $YC_CI_SECRET_ID --jq '.entries[].text_value'`
    # Выводим его в консоль
    - echo $VALUE_OF_YC_CI_SECRET_ID
